### ISSUE TITLE
Check sections/subsections representation

### ISSUE THREAD

**Issue by gcangioli** [hl7-eu/viz-lab#5]
In the SimpleChemistryResultReport example there is a section without entries and two subsections

This structure is not reflected in the viewer 

![image](https://github.com/hl7-eu/viz-lab/assets/35879607/67ef065b-aa18-437f-a5e0-11e7248ff213)

**Comment by joofio** [comment]
I think I have fixed it. please validate

**Comment by gcangioli** [comment]
it looks good now thanks
